@startuml package_diagram

hide members

note "folder db renamed\nto dao" as N1
package com.revizori.slagalica.backend <<model>> {
    package config {
        class DB <<configuration>>
    }
    package controllers {
        '
    }
    package services {
        '
    }
    package dao {
        '
    }
    package models {
        '
    }
    package utils {
        '
    }
    package dto {

    }

    config ...> dao : provides DataSource
    controllers ..> models : <<access>>
    controllers ..> services : <<access>>
    services ..> dao : <<access>>
    dao .> models : <<access>>
    controllers ...> utils : <<use>>
    services ...> utils : <<use>>
    dao ...> utils : <<use>>
    controllers ...> dto : <<use>>

    note top of controllers : Controller
    note bottom of dto : Part of model
    note bottom of dao : Part of model
    note bottom of models : Model
}
@enduml