@startuml package_diagram

hide members

note "folder db renamed\nto repositories" as N1
package com.revizori.slagalica.backend <<model>> {
    package config {
        class DB <<configuration>>
    }
    package controllers {
        '
    }
    package services {
        '
    }
    package repositories {
        '
    }
    package models {
        '
    }
    package utils {
        '
    }

    config ...> repositories : provides DataSource
    controllers --> models : <<access>>
    controllers --> services : <<access>>
    services --> repositories : <<access>>
    repositories -> models : <<access>>
    controllers ...> utils : <<use>>
    services ...> utils : <<use>>
    repositories ...> utils : <<use>>

    note top of controllers : Controller
    note bottom of repositories : Part of model
    note bottom of models : Model
}
@enduml